### ISSUE TITLE
feat request: support vim navigation keys

### ISSUE THREAD

**Issue by brandon-ja** [qualidafial/pomo#2]
right now navigating the in the tasks view uses the arrow keys.
It would be really nice if vim navigation keys were also supported:
* h = left
* j = down
* k = up
* l = left

having this supported by default would be great but it would also work to have the keybindings be configurable with a config file or something.

**Comment by qualidafial** [comment]
Fixed on the main branch. VIM h/j/k/l bindings are now supported concurrently with arrow keys, with no configuration necessary.

**Comment by dhulihan** [comment]
It would be *next level* to have the entire keymap configurable, but that's overkill :) . I use `shift+[left|right]` for terminal tab navigation so supporting `shift+hjkl` in this change is very helpful!
